language: node_js
node_js:
  - lts/dubnium
  - node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: aFDY5DKEHcjD1DGrdM/P+piC2auZvL7nvZzJw3WShjenxsozoR0IYSPkRLHSJFA2+upruJk7/Fr/IwyAFNF3xntHWieaq5DdHcSccSIYHdIdGmlUpmudo7b8+9AgxMOqFNFbZvQwaE4FI6AVT4n4O6Es0ebGXOv6/Aho0JdR9mEi5TtrFZt2om6MHOrTF/iiUDaMONKH4WfXgG+ZC8YmtUzWMkqy7jRvU5ioMq4RR7N7cufDHcZqTbbc2haoOKccQ/iU4gOz5R1CtEoaxW8OyD59gdbNve/4zDS2BjqRdKpLySsnB69+Kyqry+5Vh+S2jSSw/c/WCKWn5cFJwfLiwGOQvJD3Sjh4DPN0+WnPfO8TE95aZcSfjr10cwjcArrwZCM9iNJaOWIg8XGkZjBgmrWCdNwWuEve/s/kowyoXBlX9rZL8wW2S5UjsI/EtCZ3Fg67fpPowRgztDhEcHkLOEdo8JaS/waStj5fmOViwCfEnFPrb9ORypD9i6fa3ZZz23upyzXmV54/lUvt/gDSH6nF+434FQTWViOeQhoNTl2tU9ycmRr0P+1JL2fICArDqP/TlsntRynCAgZ1IKdKyKudq6jShSvHO2oCTTN3Wa0M58lBp1gadr1hzTs3/dFc/C/UarOJNXrrnRxmp/lCTqWrtVRvDVcCkAba34u/DfI=
  file:
    - 'unified-message-control.js'
    - 'unified-message-control.min.js'
  on:
    tags: true
